"""Initial tables

Revision ID: 25aca1993b7f
Revises: 
Create Date: 2026-05-25 10:46:41.018265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25aca1993b7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('hashed_password', sa.String(length=250), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('hashed_password')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.execute(
        "INSERT INTO admins (email, hashed_password, full_name) "
        "VALUES ('admin@example.com', 'admin123', 'Главный Админ')"
    )
    
    # 2. Добавляем тестового пользователя с фиксированным id=1
    op.execute(
        "INSERT INTO users (id, email, hashed_password, full_name) "
        "VALUES (1, 'user@example.com', 'user123', 'Иван Иванов')"
    )
    
    # 3. Создаем счет для этого пользователя (id=1, привязан к user_id=1)
    op.execute(
        "INSERT INTO accounts (id, balance, user_id) "
        "VALUES (1, 0.00, 1)"
    )
    # ### end Alembic commands ###

    op.execute("SELECT setval('users_id_seq', (SELECT MAX(id) FROM users))")
    
    # Синхронизируем счетчик для таблицы accounts
    op.execute("SELECT setval('accounts_id_seq', (SELECT MAX(id) FROM accounts))")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('admins')
    # ### end Alembic commands ###
